### ISSUE TITLE
Opening blurb suggestion

### ISSUE THREAD

**Issue by haestrod** [ElectronicsOSU/makeathon-2016#13]
From the same folks that brought you Makeathon 2015 and the fall OHI/O Hackathons comes this year’s best hardware event at Ohio State University! In this hardware focused hackathon, your goal is to make something new, amazing and fun with a group of friends. You don’t need to have a team, any hardware experience, or materials to make with before you register. What you DO need is a cool idea and openness to free food, over $1000 in prizes, and a readiness to chat with some great companies. This year’s event will be taking place at Knowlton Hall on the weekend of March 5th-6th. You want to register, your friends want to register, let's make something incredible!

**Comment by vulcant** [comment]
From the same folks that brought you Makeathon 2015 and the fall OHI/O Hackathons comes this year’s best hardware event at the <b>Ohio State University!</b> In this hardware focused hackathon, your goal is to make something new, amazing and fun with a group of friends. You don’t need to have a team, any hardware experience, or materials to make with before you register. What you DO need is a cool idea and openness to free food, over $1000 in prizes, and a readiness to chat with great companies. This year’s event will be taking place at Knowlton Hall on the weekend of March 5th-6th. You want to register, your friends want to register, let's make something incredible!
