### ISSUE TITLE
Edit navbar

### ISSUE THREAD

**Issue by DaleMitchell** [ElectronicsOSU/makeathon-2016#2]

**Comment by DaleMitchell** [comment]
In the navbar

**Comment by DaleMitchell** [comment]
Add "Sponsors" (list),

Also, "Organizers" (ElectronicsOSU, IEEE, OH-IO, Maker Club, etc.) Refer to issue #8

**Comment by vulcant** [comment]
"Hardware" at: https://docs.google.com/spreadsheets/d/1be8mGe-7cA16eylDQijJI7tm_3s7pUdKZSdfJetOt3Q/edit#gid=0
