### ISSUE TITLE
Move Projects page to year-specific URL

### ISSUE THREAD

**Issue by KevinPayravi** [ElectronicsOSU/makeathon-2016#26]
Awesome projects page! I noticed that right now, the URL is [make-oh.io/projects](http://make-oh.io/projects); what happens for 2017's projects? Should we move the page to a year-specific URL?

Example:
http://make-oh.io/projects/2016
http://make-oh.io/projects/2017
etc.

**Comment by DaleMitchell** [comment]
We do have a separate repo for 2015 (which did not have a projects page), but that doesn't necessarily mean the projects page does not have to be included in a future website. I like your example, so we'll incorporate it when it comes time to make 2017's website.

**Comment by KevinPayravi** [comment]
Nice, thanks for the reply. I'd like to push the page out on OHI/O's social media, so I'm hoping for a link that I can post now that won't break or change in the future. As long as http://make-oh.io/projects becomes a directory or something of the sort in the future, I think it'd be fine.

**Comment by DaleMitchell** [comment]
I tried fixing the /projects link for OHI/O's social media page (since Kevin said he's pointing the link to there, not 2016) but Github is acting funky. Weird.

**Comment by DaleMitchell** [comment]
Okay this should actually be fixed now lol, thank you GitHub Pages for not listing directories in a folder...
