### ISSUE TITLE
Change welcome (first) paragraph (above the register button)

### ISSUE THREAD

**Issue by DaleMitchell** [ElectronicsOSU/makeathon-2016#4]

**Comment by vulcant** [comment]
From the same folks that brought you Makeathon 2015 and the fall OHI/O Hackathons comes this year’s best hardware event. For those who are wondering, a Makeathon is a 24-hour hardware focused hackathon where the goal is to make something new, amazing and fun with a group of friends. You don’t need to have a team before you register nor do you need any hardware experience or materials to make with. You just need to have a cool idea, be open to free food and over $1000 in prizes as well as chatting with some great companies. This year’s event will be taking place at Knowlton Hall on the weekend of March 5th-6th. We know you want to register for it. We also know you want your friends to register for it.
