### ISSUE TITLE
Update Agenda

### ISSUE THREAD

**Issue by DaleMitchell** [ElectronicsOSU/makeathon-2016#7]
Develop a new agenda.

**Comment by vulcant** [comment]
<table class="table-condensed table-bordered ">
        <thead>
            <tr>
                <th>Start Time</th>
                <th>Event</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>10:00 am</td>
                <td>Check-in</td>
            </tr>
            <tr>
                <td>11:00 am</td>
                <td>Kickoff</td>
            </tr>
            <tr>
                <td>12:00 pm</td>
                <td>Making begins</td>
            </tr>
            <tr>
                <td>4:00 pm</td>
                <td>Dinner</td>
            </tr><tr>
                <td>9:00 pm</td>
                <td>Desserts & Treats</td>
            </tr>



            <tr>
                <td>12:00 am</td>
                <td>Deadline for Team Registration</td>
            </tr>
            <tr>
                <td>3:00 am</td>
                <td>Early Morning Snacks</td>
            </tr>
            <tr>
                <td>8:00 am</td>
                <td>Breakfast</td>
            </tr>
            <tr>
                <td>11:00 am</td>
                <td>Lunch</td>
            </tr>
            <tr>
                <td>12:00 pm</td>
                <td>Victory Cookies and Making ends</td>
            </tr>
            <tr>
                <td>12:15 pm</td>
                <td>Judging Begins</td>
            </tr>
            <tr>
                <td>2:15 pm</td>
                <td>Judging Ends & Lunch</td>
            </tr>
			<tr>
                <td>3:00 pm</td>
                <td>Showcase Begins</td>
            </tr>
			<tr>
                <td>4:00 pm</td>
                <td>Sleep</td>
            </tr>
        </tbody>
    </table>
